//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WEB02.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WEB02.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp đã có phát sinh. Bạn phải xóa các phát sinh liên quan trước khi xóa nhà cung cấp..
        /// </summary>
        public static string VN_ {
            get {
                return ResourceManager.GetString("VN_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không đúng định dạng (mã gồm 2 Chữ và 6 chữ số: NV-123456).
        /// </summary>
        public static string VN_CodeWrongFormat {
            get {
                return ResourceManager.GetString("VN_CodeWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        public static string VN_DataIllegal {
            get {
                return ResourceManager.GetString("VN_DataIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không được để trống.
        /// </summary>
        public static string VN_DataNull {
            get {
                return ResourceManager.GetString("VN_DataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một số đối tượng không tồn tại trong hệ trống.
        /// </summary>
        public static string VN_EntityHas {
            get {
                return ResourceManager.GetString("VN_EntityHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng không tồn tại.
        /// </summary>
        public static string VN_EntityNotFound {
            get {
                return ResourceManager.GetString("VN_EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra.
        /// </summary>
        public static string VN_Error {
            get {
                return ResourceManager.GetString("VN_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã tồn tại trong hệ thống.
        /// </summary>
        public static string VN_IsHas {
            get {
                return ResourceManager.GetString("VN_IsHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ MISA để được hỗ trợ kịp thời.
        /// </summary>
        public static string VN_MisaExceptionMsg {
            get {
                return ResourceManager.GetString("VN_MisaExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu chi không tồn tại trong hệ thống.
        /// </summary>
        public static string VN_PaymentNotFound {
            get {
                return ResourceManager.GetString("VN_PaymentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục đã có phát sinh.
        /// </summary>
        public static string VN_VendorHasPayment {
            get {
                return ResourceManager.GetString("VN_VendorHasPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp không tồn tại trong hệ thống.
        /// </summary>
        public static string VN_VendorNotFound {
            get {
                return ResourceManager.GetString("VN_VendorNotFound", resourceCulture);
            }
        }
    }
}
